create sequence devices_id_seq;

create table devices
(
    id          bigint generated by default as identity
        primary key,
    device_type varchar(32) not null
        constraint devices_device_type_check
            check ((device_type)::text = ANY
                   ((ARRAY ['GATEWAY'::character varying, 'SWITCH'::character varying, 'ACCESS_POINT'::character varying])::text[])),
    mac_address varchar(17) not null
        constraint uk_devices_mac
            unique,
    version     bigint,
    uplink_id   bigint
        constraint uplink_fk
            references devices
);

create index idx_devices_type
    on devices (device_type);

create index idx_devices_uplink
    on devices (uplink_id);




